/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 formila-e.gltf --transform 
Files: formila-e.gltf [3.65MB] > formila-e-transformed.glb [2.14MB] (41%)
Author: 3dblenderlol (https://sketchfab.com/3dblenderlol)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/formula-e-jaguar-i-type-4-c722e175f91240a88eec2d777b6d503f
Title: Formula E  [Jaguar I Type-4]
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/formulae-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
        position={[-0.798, 0.093, 0.791]}
        rotation={[0.047, 0.027, 0]}
        scale={[0.159, 0.07, 0.069]}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.PaletteMaterial002}
        position={[-0.798, 0.093, 0.791]}
        rotation={[0.047, 0.027, 0]}
        scale={[0.159, 0.07, 0.069]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Carbon_Fibre}
        position={[-0.798, 0.093, 0.791]}
        rotation={[0.047, 0.027, 0]}
        scale={[0.159, 0.07, 0.069]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.PaletteMaterial003}
        position={[-0.914, -0.19, 2.081]}
        scale={0.013}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.PaletteMaterial004}
        position={[-0.151, -0.388, 0.269]}
        rotation={[-0.01, 0, 0]}
        scale={[0.009, 0.021, 0.022]}
      />
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials.PaletteMaterial005}
        position={[-0.92, 0.156, -1.443]}
        rotation={[1.46, 0, 0]}
        scale={[0.181, 1.047, 0.258]}
      />
      <mesh
        geometry={nodes.Object_17.geometry}
        material={materials["Material.004"]}
        position={[-0.92, 0.156, -1.443]}
        rotation={[1.46, 0, 0]}
        scale={[0.181, 1.047, 0.258]}
      />
      <mesh
        geometry={nodes.Object_21.geometry}
        material={materials.PaletteMaterial006}
        position={[-0.485, -0.113, 0.148]}
        rotation={[0, 0.001, 0.003]}
        scale={[0.08, 0.084, 0.076]}
      />
      <mesh
        geometry={nodes.Object_24.geometry}
        material={materials.PaletteMaterial007}
        position={[-0.687, -0.038, 1.482]}
        rotation={[2.945, -0.405, -0.028]}
        scale={[0.027, 0.007, 0.018]}
      />
      <mesh
        geometry={nodes.Object_29.geometry}
        material={materials.PaletteMaterial008}
        position={[-0.904, -0.318, -2.033]}
        scale={0.008}
      />
      <mesh
        geometry={nodes.Object_35.geometry}
        material={materials.PaletteMaterial009}
        position={[-0.84, 0.366, -0.489]}
        rotation={[-3.119, 0, 0]}
        scale={[-0.016, 0.01, 0.028]}
      />
      <mesh
        geometry={nodes.Object_36.geometry}
        material={materials["Material.009"]}
        position={[-0.84, 0.366, -0.489]}
        rotation={[-3.119, 0, 0]}
        scale={[-0.016, 0.01, 0.028]}
      />
      <mesh
        geometry={nodes.Object_41.geometry}
        material={materials.PaletteMaterial010}
        position={[-0.243, -0.172, 1.292]}
        rotation={[0, 0, Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Object_59.geometry}
        material={materials.Panasonic}
        position={[-0.107, -0.056, -0.884]}
        rotation={[1.601, 0, -1.419]}
        scale={0.133}
      />
      <mesh
        geometry={nodes.Object_65.geometry}
        material={materials.Formulae}
        position={[-0.919, -0.128, 2.098]}
        rotation={[0.303, -0.004, -0.013]}
        scale={[0.125, 0.145, 0.145]}
      />
      <mesh
        geometry={nodes.Object_68.geometry}
        material={materials["panasonic-logo-black-and-white-1"]}
        position={[-0.92, -0.007, 1.653]}
        rotation={[0.231, -0.002, -0.009]}
        scale={0.249}
      />
      <mesh
        geometry={nodes.Object_70.geometry}
        material={materials.julius_baer}
        position={[-0.92, -0.078, 1.933]}
        rotation={[0.273, 0, 0]}
        scale={[0.086, 0.095, 0.095]}
      />
      <mesh
        geometry={nodes.Object_72.geometry}
        material={materials.material}
        position={[-0.92, -0.037, 1.782]}
        rotation={[0.238, 0, 0]}
        scale={0.128}
      />
      <mesh
        geometry={nodes.Object_78.geometry}
        material={materials.PaletteMaterial011}
        position={[-0.92, -0.098, -2.646]}
        rotation={[1.447, 0, 0]}
        scale={[0.007, 0.011, 0.008]}
      />
      <mesh
        geometry={nodes.Object_81.geometry}
        material={materials.Jaguar}
        position={[-0.92, -0.179, 2.253]}
        rotation={[0.349, 0, 0]}
        scale={0.073}
      />
    </group>
  );
}

useGLTF.preload("/formulae-transformed.glb");
